### ISSUE TITLE
Unable to Install using brew

### ISSUE THREAD

**Issue by Tweetsauceyeep** [koekeishiya/yabai#1208]
So Im trying to install Yabai using brew. (Im on High Sierra) 
I have successfully installed it before but I ended up deleting it. Im now trying to install it again but I run into this error.

```
`brew install koekeishiya/formulae/yabai
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 4 formulae.

Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://github.com/koekeishiya/yabai/releases/download/v4.0.0/ya
Already downloaded: /Users/Sia/Library/Caches/Homebrew/downloads/c729621f1f1224f4082f68cc2ab116270ee7a204b621cad13c5abce5aaec995c--yabai-v4.0.0.tar.gz
==> Installing yabai from koekeishiya/formulae
tar: Ignoring malformed pax extended attribute
tar: Error exit delayed from previous errors.
Error: Failure while executing; `tar --extract --no-same-owner --file /Users/Sia/Library/Caches/Homebrew/downloads/c729621f1f1224f4082f68cc2ab116270ee7a204b621cad13c5abce5aaec995c--yabai-v4.0.0.tar.gz --directory /private/tmp/d20220324-7285-12w14s5` exited with 1. Here's the output:
tar: Ignoring malformed pax extended attribute
tar: Error exit delayed from previous errors.
```

**Comment by elmimmo** [comment]
Same here:

```
$ brew install koekeishiya/formulae/yabai
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated Homebrew from 40e3a47f1 to 33709297c.
Updated 5 taps (homebrew/cask-versions, homebrew/core, homebrew/cask, homebrew/cask-fonts and homebrew/services).
==> New Formulae
(…)

==> Homebrew was updated to version 3.4.5
The changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/3.4.5
==> Tapping koekeishiya/formulae
Cloning into '/usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae'...
remote: Enumerating objects: 316, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 316 (delta 30), reused 36 (delta 16), pack-reused 263
Receiving objects: 100% (316/316), 45.53 KiB | 308.00 KiB/s, done.
Resolving deltas: 100% (179/179), done.
Tapped 3 formulae (14 files, 63.8KB).
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://github.com/koekeishiya/yabai/releases/download/v4.0.0/y
==> Downloading from https://objects.githubusercontent.com/github-production-re
######################################################################## 100.0%
==> Installing yabai from koekeishiya/formulae
tar: Ignoring malformed pax extended attribute
tar: Error exit delayed from previous errors.
Error: Failure while executing; `tar --extract --no-same-owner --file /Users/jorge/Library/Caches/Homebrew/downloads/c729621f1f1224f4082f68cc2ab116270ee7a204b621cad13c5abce5aaec995c--yabai-v4.0.0.tar.gz --directory /private/tmp/d20220404-3226-jpjq5f` exited with 1. Here's the output:
tar: Ignoring malformed pax extended attribute
tar: Error exit delayed from previous errors.

**Comment by apoteosi** [comment]
Same here on 10.14; something appears to be broken in relation to the tarball but surely there's a workaround for us?

**Comment by yao177** [comment]
```shell
➜  ~ brew install koekeishiya/formulae/yabai
Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

==> Downloading https://github.com/koekeishiya/yabai/releases/download/v4.0.1/ya
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
==> Installing yabai from koekeishiya/formulae
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 11.3.1.

tar: Ignoring malformed pax extended attribute
tar: Error exit delayed from previous errors.
Error: Failure while executing; `tar --extract --no-same-owner --file /Users/yao/Library/Caches/Homebrew/downloads/a675bc5a7a62231f314fdefaad0d2d9f974490bc94eb5b16ba19e6f65b53156b--yabai-v4.0.1.tar.gz --directory /private/tmp/d20220610-16627-9cc272` exited with 1. Here's the output:
tar: Ignoring malformed pax extended attribute
tar: Error exit delayed from previous errors.
```
Same as macOS 10.14.

**Comment by SethMcBean** [comment]
Same as #1216 requiring updated libarchive install.

**Comment by thomasvercoe** [comment]
same as #1216

**Comment by pclalv** [comment]
I'm unable to `brew install` yabai, too. while I wish that it just worked :tm:, I also discovered a work around.

```sh-session
# brew install --debug koekeishiya/formulae/yabai
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/yabai.rb
==> Downloading https://github.com/koekeishiya/yabai/releases/download/v4.0.4/yabai-v4.0.4.tar.gz
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.5.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/koekeishiya/yabai/releases/download/v4.0.4/yabai-v4.0.4.tar.gz
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/b0078d810c2572ae6b96e4efddde18bca329a18ebc0aa292b6703f8c15595649--yabai-v4.0.4.tar.gz
==> Installing yabai from koekeishiya/formulae
Error: The following formula cannot be installed from bottle and must be
built from source.
  yabai
Install the Command Line Tools:
  xcode-select --install

/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:383:in `install'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:212:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:333:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/install.rb:323:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:322:in `each'
/usr/local/Homebrew/Library/Homebrew/install.rb:322:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:226:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

I then ran `open` on the tar file that Homebrew downloaded, `/Users/me/Library/Caches/Homebrew/downloads/b0078d810c2572ae6b96e4efddde18bca329a18ebc0aa292b6703f8c15595649--yabai-v4.0.4.tar.gz`, which ran successfully.

that file seems to contain a working yabai executable, docs, and examples, so I just moved them to where I wanted them.

so it seems that the tar file is fine - I feel disappointed that brew doesn't seem to indicate at all _why_ yabai can't be installed from the bottle.

**Comment by giabertu** [comment]
> I'm unable to `brew install` yabai, too. while I wish that it just worked ™️, I also discovered a work around.
> 
> ```
> # brew install --debug koekeishiya/formulae/yabai
> /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/yabai.rb
> ==> Downloading https://github.com/koekeishiya/yabai/releases/download/v4.0.4/yabai-v4.0.4.tar.gz
> /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.5.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/koekeishiya/yabai/releases/download/v4.0.4/yabai-v4.0.4.tar.gz
> Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/b0078d810c2572ae6b96e4efddde18bca329a18ebc0aa292b6703f8c15595649--yabai-v4.0.4.tar.gz
> ==> Installing yabai from koekeishiya/formulae
> Error: The following formula cannot be installed from bottle and must be
> built from source.
>   yabai
> Install the Command Line Tools:
>   xcode-select --install
> 
> /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:383:in `install'
> /usr/local/Homebrew/Library/Homebrew/upgrade.rb:212:in `install_formula'
> /usr/local/Homebrew/Library/Homebrew/install.rb:333:in `install_formula'
> /usr/local/Homebrew/Library/Homebrew/install.rb:323:in `block in install_formulae'
> /usr/local/Homebrew/Library/Homebrew/install.rb:322:in `each'
> /usr/local/Homebrew/Library/Homebrew/install.rb:322:in `install_formulae'
> /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:226:in `install'
> /usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

> 
> I then ran `open` on the tar file that Homebrew downloaded, `/Users/me/Library/Caches/Homebrew/downloads/b0078d810c2572ae6b96e4efddde18bca329a18ebc0aa292b6703f8c15595649--yabai-v4.0.4.tar.gz`, which ran successfully.
> 
> that file seems to contain a working yabai executable, docs, and examples, so I just moved them to where I wanted them.
> 
> so it seems that the tar file is fine - I feel disappointed that brew doesn't seem to indicate at all _why_ yabai can't be installed from the bottle.

I had the same issue @pclalv. Running  ```xcode-select --install``` and installing the command line developer tools, then running ```brew install koekeishiya/formulae/yabai``` again solved it.
