### ISSUE TITLE
skhd should be uninstalled before yabai

### ISSUE THREAD

**Issue by acehinnnqru** [koekeishiya/yabai#1630]
Device: M1 Max
OS Version: Ventura

Error:
```
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/installed_dependents.rb:46:in `find_some_installed_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:111:in `check_for_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:104:in `handle_unsatisfied_dependents'
/opt/homebrew/Library/Homebrew/uninstall.rb:14:in `uninstall_kegs'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:60:in `uninstall'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>`
```

1. Stop skhd and yabai first
2. Try to remove skhd
3. If it also report error, then just restart computer and remove stop and remove skhd again
4. Then remove the yabai

**Comment by koekeishiya** [comment]
No idea what this is about. There is no dependency between yabai and skhd. They are separate pieces of software that both run indepedently.
